apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.projectID | quote }}
      auth:
        workloadIdentityFederation:
          serviceAccountRef:
            name: {{ .Values.serviceAccountName | quote }}
            namespace: {{ .Values.serviceAccountNamespace | quote }}
          audience: {{ .Values.audience | quote }}