---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgABPMqSsBrv65gZmHv7tjNHKei1ltV4MyR8v8xDM9q04IGw8+Db8vXq+ufX0wOTlY7o+JZev5ojzG9W8741w0H5XN+gIUkYwDlQuwAI7Bp7C17CvoJAwC8du5BGH6rVEGUgLcmn2Gc2X3wQIeHX9Ef8vfyUYVMkUwRjfATCPdK4rjAt6LHI3Jf4Niv/71LSuXQe5j0AhOUvCjTvMQezWzstcfg7sA6DyUbvmeJYsO/p0hTI9AY5dAv3BGVJhv3sUxszHTqy9mbx2Tpa8i6E4dn/qA3aNPM67zr/uUPq1wl2zMo6i1Cukg5J90SaOwocaTDJolC41b1BiQRyH0uqpA17vYqOFXHVfnFH0jgscpIaVyaLOgDQwuUw77CnKpI0r8EcwIUQoiKo43ghm8IdxkwXdu0vRKzx0ysdt3YFW2t3ko77diGgN81pmeGQVTW0zE00fPR7GQWPhdqMRd1xdORWmrC3GVWIGJH+mR6Sfg5mzgbHsGqNmusltyRB3OupuW3YICc/yMYgYHAf4q/zO3k6cJfuAc76InCZcbb+crIkVJQj0/JSvHdLXC8sVBrqu71tlZokK0Uz1CSsdLnWbUe0vbZSACLp4n0I+ukynEovpX1pCNhqfGt1KHYeudIuW2xUEq/gb301i7cHSMXZKlRi6nqrbr1jsJYc43k1UCGZuKG/d0MKgMDF0yJnbBnfyUU2s7WdIQWUr8I6zHzTDe36Iw==
  template:
    metadata:
      name: n8n-secret
      namespace: n8n
    type: Opaque
