---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgA2LhLPyZVKCyaoh6bZ9MNtLVyQbkA2Jkh9NNxF8Jfb/cvRDKJjOgM+1fB2P/NyTPh0vc6rnqyf40q99w3hBW6FODTYcq5ydZ1Qtxmof5NGNipP+roufZfI0+6Ju8ySU4ISClIwbzHWKKPlu6YzU2E+uy0XIFE+f6zA3IIa6ApWtC12Lb2DvbEK+F/LWG7+Bt2X/G1rpCz7DTaay/hxLGbPrFXZvsoP0646545Hd07gO7mt3MtA7rX+cgnE37G14GwjHjT4LZjloXziRh/nrB/ZN0uwvDpmWZn+3eM+lKV00X7rA+a2nDxrTo9tzBrkP0dvbdDLzUzZOe2WgWp+wTWDZQr3evPSq4yMY21V1G7pYxf2Ndu03EBdnS52iub7z5cGg7HkN4MIsxRKZIyv26zvPTueazj/8Wos9VZ0UaJfo9C9Z/LmMtQJktTR/cPaX5jyqHK7kuctzVBavFivyuJr63NpdzPkP63w4R7RLS2pIlTC7zs9vqayfTNepgZIHcvJLTZpi0BnZkwiJs480+yj9Ttuywlnze5/5xvcQ8yaG5+/ULoFFlNF9d7o2VRshlp4oD5zfhjiDItnVnHB2LwjNUSr1sFuKoGOnhms31NPpjGftRnb6ja9za9Va/Z0iFhDLn5Z8uxFMjnBou48gtxTuGqhuXJyIC4ClsNsbZnBo2PszL5vu+IrWNTdaeF607IgVupq50lwZAZW1FDHGXL2sA==
  template:
    metadata:
      name: n8n-secret
      namespace: n8n
    type: Opaque
