---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgDU994ks1Er7swBpgE6fgHkKraUtOxrd441L8RvQrQ4hyzNAqH39g6H8dzod/choi0e2DPxWNRWkCoLxby7CJZ8IHbTwFvuUnN+FiowaP2LwdyK4/YlHvVBtEP4Z/yRDdjgBkUK9dQiq5Y0O5/z8d+uhFZ1VU71L6BF4Ckg/7rCkGPZB4N3gjN/KyKygnABjv+bGzmyYOXXuGuKkSmh45NMOJvMOohjLrR7wLr4msYfgPE9MMoNY1qzKNhcybcpvL4u7JkK8N2U/Wviic6wgDVlouJnrKQifbI0EqsHSpMf2jGV8tXbJxyWbHP9g5Y4df2QNJcUE7W7TVYgN3PzMduPbXl+IqeGBH6YIyYzbA7c7yS8ooY6NgAT0Etl+nzmfTC/nrpixOzk8bv8MRQGrK8u56gmqTVGiC5ziOf3W41xTYbebCQZmc0UixLrV4wWyGJ+wNQ6V3FHIrgZBeKIn1hjrT018usLLN2c82AnMZ1UxVAG539hKwQ2WxOpKxwTOqgMY4akyjYyxS1tOar0dQFUUJRC9F1YTX7EXaYqXge++Evs0Yu1jwItFNyVhM/cH7oO5YRHwOVbRDvX4pc/oURUe+AwFyniYMcRU5xLNHr8vLTXCBngAjmAyTcHkgwFyyj0Umt/AEoHeAu8T9IUsh0q/a7uLy/cowZ5gXWr1c6E+HQalV5ZokTSQpUevip79dKSASObGqDmDNhc5N+DMDJyhA==
  template:
    metadata:
      name: n8n-secret
      namespace: n8n
    type: Opaque
