apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secret
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform-secrets
  target:
    name: n8n-secret
    creationPolicy: Owner
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: home-garage-n8n-encryption-key
