apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: platform-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    gcpsm:
      projectID: {{gcpProjectId}}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{gcpServiceAccountName}}
            namespace: {{gcpServiceAccountNamespace}}
