apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: platform-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    infisical:
      hostAPI: {{infisicalHostApi}}
      auth:
        universalAuthCredentials:
          clientId:
            name: {{credentialsSecretName}}
            namespace: {{credentialsNamespace}}
            key: clientId
          clientSecret:
            name: {{credentialsSecretName}}
            namespace: {{credentialsNamespace}}
            key: clientSecret
      secretsScope:
        projectSlug: {{projectSlug}}
        environmentSlug: {{environmentSlug}}
        secretsPath: {{secretsPath}}
        recursive: false
