apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: cloudflare-tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: CLOUDFLARE_TUNNEL_TOKEN
