apiVersion: v1
kind: Namespace
metadata:
  name: demo

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-external-secret
  namespace: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  # target は ESO が Kubernetes 上に作成・更新する Secret の出力先を表す
  target:
    name: k3s-app-secret
  # data は 外部 Secret のどの値を Kubernetes Secret のどのキーへ対応付けるかを表す
  data:
  - secretKey: my-db-pass # Kubernetes Secret 上のキーを指定
    remoteRef:
      key: my-test-password # GCP の Secret Manager 上の Secret のキーを指定
