apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps.yaml
  - platform-core.yaml
  - platform-networking.yaml
  - platform-observability-metrics.yaml
  - platform-observability-logging.yaml
  - platform-observability-tracing.yaml
