apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform-secrets
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: home-garage-n8n-postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: home-garage-n8n-postgres-password
    - secretKey: POSTGRES_NON_ROOT_USER
      remoteRef:
        key: home-garage-n8n-postgres-non-root-user
    - secretKey: POSTGRES_NON_ROOT_PASSWORD
      remoteRef:
        key: home-garage-n8n-postgres-non-root-password
