apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: n8n
  labels:
    service: postgres-n8n
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    service: postgres-n8n
