apiVersion: v2
name: argocd-config
description: ArgoCD configuration managed by ArgoCD
type: application
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 9.3.7
    repository: https://argoproj.github.io/argo-helm